import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { parse, type ParseError } from "jsonc-parser";
import { DEFAULT_PRIVATE_PATHS } from "./sandbox/default-private-paths.js";
import type { CommandPolicy, HeimdallConfig } from "./types.js";

export const OPT_OUT_GUARD_IDS = [
	"secret-guard",
	"command-policy-guard",
	"env-protect",
	"kubectl-secret-guard",
	"sops-secret-guard",
	"fnox-secret-guard",
] as const;

const DEFAULT_CONFIG_BASENAME = "default";
const USER_CONFIG_BASENAME = "config";
const PROJECT_CONFIG_BASENAME = "heimdall";
/** Legacy agent-owned project dirs, merged in this order (later wins). */
const LEGACY_PROJECT_DIRS = [".pi", ".omp", ".dsh"] as const;

/**
 * Plain layer merge, exactly as before: nested objects recurse, arrays
 * CONCATENATE in layer order (deny/writable are ordered last-match-wins
 * negation lists — entries may repeat across layers to re-assert over
 * intervening `!` negations, so never dedupe here), scalars replace.
 * Duplicate cleanup happens in `canonicalizeUniversalFile` at the file
 * level, never in the merge.
 */
export function deepMerge(base: HeimdallConfig, overrides: HeimdallConfig): HeimdallConfig {
	const result = { ...base };
	for (const key of Object.keys(overrides) as (keyof HeimdallConfig)[]) {
		const ov = overrides[key];
		if (ov === undefined) continue;
		const bv = base[key];
		if (
			typeof ov === "object" && ov !== null && !Array.isArray(ov) &&
			typeof bv === "object" && bv !== null && !Array.isArray(bv)
		) {
			(result as Record<string, unknown>)[key] = deepMerge(
				bv as HeimdallConfig,
				ov as HeimdallConfig,
			);
		} else if (Array.isArray(ov) && Array.isArray(bv)) {
			(result as Record<string, unknown>)[key] = [...bv, ...ov];
		} else {
			(result as Record<string, unknown>)[key] = ov;
		}
	}
	return result;
}

export function parseConfig(raw: string): HeimdallConfig | null {
	try {
		const errors: ParseError[] = [];
		const parsed = parse(raw, errors, { allowTrailingComma: true });
		if (errors.length === 0 && parsed && typeof parsed === "object") return parsed;
	} catch {
		// Parse error — skip
	}
	return null;
}

function findRepoRoot(cwd: string): string | undefined {
	let dir = resolve(cwd);
	for (;;) {
		if (existsSync(join(dir, ".git"))) return dir;
		const parent = dirname(dir);
		if (parent === dir) return undefined;
		dir = parent;
	}
}

/**
 * Load a config level from `dir`, merging BOTH spellings when present:
 * `basename.json` is the base and `basename.jsonc` overrides it. Returns the
 * effective path (jsonc when it exists, else json) plus the merged config.
 */
function loadConfigLevel(dir: string, basename: string): { path: string | undefined; config: HeimdallConfig | null } {
	const jsonPath = join(dir, `${basename}.json`);
	const jsoncPath = join(dir, `${basename}.jsonc`);
	const jsonConfig = loadConfigFile(existsSync(jsonPath) ? jsonPath : undefined);
	const jsoncConfig = loadConfigFile(existsSync(jsoncPath) ? jsoncPath : undefined);
	if (!jsonConfig && !jsoncConfig) return { path: undefined, config: null };
	return {
		path: existsSync(jsoncPath) ? jsoncPath : jsonPath,
		config: jsoncConfig ? deepMerge(jsonConfig ?? {}, jsoncConfig) : jsonConfig,
	};
}

export function loadConfigFile(path: string | undefined): HeimdallConfig | null {
	if (!path || !existsSync(path)) return null;
	return parseConfig(readFileSync(path, "utf-8"));
}

export function defaultConfigText(): string {
	const denyList = DEFAULT_PRIVATE_PATHS.map((path) => `\t\t\t\t${JSON.stringify(path)}`).join(",\n");
	return `// Generated by pi-heimdall for transparency.\n// This file may be overwritten when Heimdall starts.\n// Put local changes in ${USER_CONFIG_BASENAME}.jsonc or a project .config/heimdall.json file.\n{\n\t"sandbox": {\n\t\t"enabled": false,\n\t\t"useDefaultFilesystemDeny": true,\n\t\t"sshAgent": false,\n\t\t"gpgAgent": false,\n\t\t"ageAgent": false,\n\t\t"filesystem": {\n\t\t\t"deny": [\n${denyList}\n\t\t\t],\n\t\t\t"writable": [\n\t\t\t\t"~/.pi"\n\t\t\t]\n\t\t}\n\t}\n}\n`;
}

function heimdallConfigDir(): string {
	return join(homedir(), ".config", "heimdall");
}

function generatedDefaultConfigPath(configDir: string): string {
	return join(configDir, `${DEFAULT_CONFIG_BASENAME}.jsonc`);
}

export function ensureGeneratedDefaultConfig(configDir: string = heimdallConfigDir()): string {
	mkdirSync(configDir, { recursive: true });
	const defaultPath = generatedDefaultConfigPath(configDir);
	writeFileSync(defaultPath, defaultConfigText());
	return defaultPath;
}

function withoutGeneratedDeny(config: HeimdallConfig): HeimdallConfig {
	return {
		...config,
		sandbox: {
			...config.sandbox,
			filesystem: {
				...config.sandbox?.filesystem,
				deny: [],
			},
		},
	};
}

export function mergeConfigLevels(defaultConfig: HeimdallConfig | null, userConfig: HeimdallConfig | null, projectConfig: HeimdallConfig | null): HeimdallConfig {
	let merged = deepMerge(defaultConfig ?? {}, userConfig ?? {});
	merged = deepMerge(merged, projectConfig ?? {});

	if (merged.sandbox?.useDefaultFilesystemDeny === false && defaultConfig) {
		merged = deepMerge(withoutGeneratedDeny(defaultConfig), userConfig ?? {});
		merged = deepMerge(merged, projectConfig ?? {});
	}

	return merged;
}

export interface EffectiveConfig {
	config: HeimdallConfig;
	defaultConfigPath: string;
	userConfigPath: string | undefined;
	projectConfigPath: string | undefined;
	/** Migration problems: unparseable legacy files kept in place. */
	migrationErrors: string[];
}

/**
 * Legacy user-level config files across all runtimes (pi, omp, dsh).
 * `sources` merge into the universal user config; `staleDefaults` are
 * generated files — delete-only, never merged (regenerated at the new
 * location on every start).
 */
function legacyUserConfigFiles(): { sources: string[]; staleDefaults: string[] } {
	const home = homedir();
	const agentDirs = [join(home, ".pi", "agent"), join(home, ".omp", "agent")];
	const sources: string[] = [];
	for (const dir of agentDirs) {
		for (const name of ["heimdall.json", "heimdall.jsonc"]) {
			const p = join(dir, name);
			if (existsSync(p)) sources.push(p);
		}
	}
	// DSH's user-global file lives directly under its home dir.
	for (const name of ["heimdall.json", "heimdall.jsonc"]) {
		const p = join(home, ".dsh", name);
		if (existsSync(p)) sources.push(p);
	}
	// Generated defaults are regenerated, not migrated: delete-only, never merged.
	const staleDefaults: string[] = [];
	for (const dir of agentDirs) {
		const p = join(dir, "heimdall.default.jsonc");
		if (existsSync(p)) staleDefaults.push(p);
	}
	return { sources, staleDefaults };
}
function legacyProjectConfigFiles(repoRoot: string): string[] {
	const files: string[] = [];
	for (const dir of LEGACY_PROJECT_DIRS) {
		for (const name of ["heimdall.json", "heimdall.jsonc"]) {
			const p = join(repoRoot, dir, name);
			if (existsSync(p)) files.push(p);
		}
	}
	return files;
}

/**
 * Mandatory one-way migration. When the universal target exists, the legacy
 * files are dead weight and simply deleted. When it does not and legacy
 * files exist, they are merged (dir order `.pi` → `.omp` → `.dsh`; per dir,
 * JSON is the base and JSONC overrides it), written to the universal
 * location, and the legacy files are deleted. There is no fallback read —
 * after this function returns, only universal locations are consulted.
 */
function migrate(
	legacyFiles: string[],
	targetDir: string,
	targetBasename: string,
): string | undefined {
	if (legacyFiles.length === 0) return undefined;
	// Unparseable legacy files are never merged or deleted — the caller
	// classifies and reports them, this function only honors the skip.
	const unparseable = legacyFiles.filter((file) => loadConfigFile(file) === null);
	const parseable = legacyFiles.filter((file) => !unparseable.includes(file));
	if (parseable.length === 0) return undefined; // nothing to migrate
	let merged: HeimdallConfig | null = null;
	for (const file of parseable) {
		merged = deepMerge(merged ?? {}, loadConfigFile(file) ?? {});
	}
	mkdirSync(targetDir, { recursive: true });
	const targetPath = join(targetDir, `${targetBasename}.json`);
	writeFileSync(targetPath, `${JSON.stringify(merged ?? {}, null, "\t")}\n`);
	for (const file of parseable) {
		try {
			rmSync(file, { force: true });
		} catch (err) {
			if ((err as NodeJS.ErrnoException).code !== "ENOENT") {
				throw new Error(`heimdall: failed to remove migrated config ${file}: ${(err as Error).message}`);
			}
		}
	}
	return targetPath;
}

/**
 * Canonicalize a universal config file already on disk: rewrite it whenever
 * any array differs from its order-preserving deduped form (heals files
 * written by an earlier merge that concatenated naive duplicates). Returns
 * the path when rewritten.
 */
function canonicalizeUniversalFile(path: string): string | undefined {
	const config = loadConfigFile(path);
	if (!config) return undefined;
	let changed = false;
	const canonical = structuredClone(config) as HeimdallConfig;
	// Schema-aware file heal: commandPolicies dedupe by `name` identity
	// (CommandPolicy schema). String lists dedupe exact repeats keeping the
	// LAST occurrence: deny/writable are ordered last-match-wins negation
	// lists, so a later repeat may re-assert over intervening `!` negations
	// and must keep its position. Never reorder.
	if (canonical.commandPolicies) {
		const byName = new Map<string, CommandPolicy>();
		for (const policy of canonical.commandPolicies) byName.set(policy.name, policy);
		if (byName.size !== canonical.commandPolicies.length) {
			canonical.commandPolicies = [...byName.values()];
			changed = true;
		}
	}
	const dedupeKeepLast = (list: string[]): string[] => {
		const lastIndex = new Map<string, number>();
		list.forEach((entry, i) => lastIndex.set(entry, i));
		return list.filter((entry, i) => lastIndex.get(entry) === i);
	};
	if (canonical.disabled && new Set(canonical.disabled).size !== canonical.disabled.length) {
		canonical.disabled = dedupeKeepLast(canonical.disabled);
		changed = true;
	}
	for (const list of ["allow", "deny"] as const) {
		const current = canonical.sandbox?.env?.[list];
		if (Array.isArray(current) && new Set(current).size !== current.length) {
			canonical.sandbox!.env![list] = dedupeKeepLast(current);
			changed = true;
		}
	}
	for (const list of ["deny", "writable"] as const) {
		const current = canonical.sandbox?.filesystem?.[list];
		if (Array.isArray(current) && new Set(current).size !== current.length) {
			canonical.sandbox!.filesystem![list] = dedupeKeepLast(current);
			changed = true;
		}
	}
	if (!changed) return undefined;
	writeFileSync(path, `${JSON.stringify(canonical, null, "\t")}\n`);
	return path;
}

/** Migrate the user-level config; returns the target path when written. */
export function migrateUserConfig(configDir: string = heimdallConfigDir(), migrationErrors: string[] = []): string | undefined {
	const { sources, staleDefaults } = legacyUserConfigFiles();
	const target = loadConfigLevel(configDir, USER_CONFIG_BASENAME);
	// Unparseable legacy files may hold fixable content — never delete them.
	const unparseable = [...sources, ...staleDefaults].filter((file) => loadConfigFile(file) === null);
	if (unparseable.length > 0) {
		migrationErrors.push(`unparseable legacy user config kept in place, fix or remove: ${unparseable.join(", ")}`);
	}
	if (target.path) {
		// Universal config exists — parseable legacy files are dead weight.
		for (const file of [...sources, ...staleDefaults]) {
			if (!unparseable.includes(file)) rmSync(file, { force: true });
		}
		canonicalizeUniversalFile(target.path);
		return undefined;
	}
	const written = migrate(sources, configDir, USER_CONFIG_BASENAME);
	if (written) canonicalizeUniversalFile(written);
	for (const file of staleDefaults) {
		if (!unparseable.includes(file)) rmSync(file, { force: true });
	}
	return written;
}

/** Migrate the project-level config; returns the target path when written. */
export function migrateProjectConfig(cwd: string, migrationErrors: string[] = []): string | undefined {
	const repoRoot = findRepoRoot(cwd) ?? cwd;
	const targetDir = join(repoRoot, ".config");
	const target = loadConfigLevel(targetDir, PROJECT_CONFIG_BASENAME);
	const stale = legacyProjectConfigFiles(repoRoot);
	// Unparseable legacy files may hold fixable content — never delete them.
	const unparseable = stale.filter((file) => loadConfigFile(file) === null);
	if (unparseable.length > 0) {
		migrationErrors.push(`unparseable legacy project config kept in place, fix or remove: ${unparseable.join(", ")}`);
	}
	if (target.path) {
		// Universal config exists — parseable legacy files are dead weight.
		for (const file of stale) {
			if (!unparseable.includes(file)) rmSync(file, { force: true });
		}
		canonicalizeUniversalFile(target.path);
		return undefined;
	}
	const written = migrate(stale, targetDir, PROJECT_CONFIG_BASENAME);
	if (written) canonicalizeUniversalFile(written);
	return written;
}

function findProjectConfigPath(cwd: string): string | undefined {
	const repoRoot = findRepoRoot(cwd) ?? cwd;
	return loadConfigLevel(join(repoRoot, ".config"), PROJECT_CONFIG_BASENAME).path;
}

/**
 * Read-only sibling of loadEffectiveConfig: reads the same three levels
 * without writing generated defaults or migrating legacy files. Missing
 * levels merge as empty.
 */
export function readEffectiveConfig(cwd: string, configDir: string = heimdallConfigDir()): EffectiveConfig {
	const userLevel = loadConfigLevel(configDir, USER_CONFIG_BASENAME);
	const projectConfigPath = findProjectConfigPath(cwd);
	const defaultConfigPath = generatedDefaultConfigPath(configDir);
	return {
		config: mergeConfigLevels(loadConfigFile(defaultConfigPath), userLevel.config, loadConfigFile(projectConfigPath)),
		defaultConfigPath,
		userConfigPath: userLevel.path,
		projectConfigPath,
		migrationErrors: [],
	};
}

/**
 * Load the effective config. Fixed locations only — agent-owned legacy paths
 * (`.pi/`, `.omp/`, `.dsh/`, `~/.pi/agent/`) are migrated (merged, written to
 * the universal location, deleted) and never read:
 *   - Generated defaults: ~/.config/heimdall/default.jsonc
 *   - User-level:         ~/.config/heimdall/config.jsonc (fallback: config.json)
 *   - Project-level:      repo root .config/heimdall.json (fallback: .json)
 */
export function loadEffectiveConfig(cwd: string, configDir: string = heimdallConfigDir()): EffectiveConfig {
	const defaultConfigPath = ensureGeneratedDefaultConfig(configDir);
	// Migration problems must not kill the config load — guards stay active
	// on universal content; errors surface to the session via the collector.
	const migrationErrors: string[] = [];
	migrateUserConfig(configDir, migrationErrors);
	migrateProjectConfig(cwd, migrationErrors);

	const userLevel = loadConfigLevel(configDir, USER_CONFIG_BASENAME);
	const projectConfigPath = findProjectConfigPath(cwd);

	return {
		config: mergeConfigLevels(loadConfigFile(defaultConfigPath), userLevel.config, loadConfigFile(projectConfigPath)),
		defaultConfigPath,
		userConfigPath: userLevel.path,
		projectConfigPath,
		migrationErrors,
	};
}