import { getAgentDir } from "@earendil-works/pi-coding-agent";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { parse, type ParseError } from "jsonc-parser";
import { DEFAULT_PRIVATE_PATHS } from "./sandbox/default-private-paths.js";
import type { HeimdallConfig } from "./types.js";

export const OPT_OUT_GUARD_IDS = [
	"secret-guard",
	"command-policy-guard",
	"env-protect",
	"kubectl-secret-guard",
	"sops-secret-guard",
] as const;

const DEFAULT_CONFIG_BASENAME = "heimdall.default";
const USER_CONFIG_BASENAME = "heimdall";

export function deepMerge(base: HeimdallConfig, overrides: HeimdallConfig): HeimdallConfig {
	const result = { ...base };
	for (const key of Object.keys(overrides) as (keyof HeimdallConfig)[]) {
		const ov = overrides[key];
		if (ov === undefined) continue;
		const bv = base[key];
		if (
			typeof ov === "object" && ov !== null && !Array.isArray(ov) &&
			typeof bv === "object" && bv !== null && !Array.isArray(bv)
		) {
			(result as Record<string, unknown>)[key] = deepMerge(
				bv as HeimdallConfig,
				ov as HeimdallConfig,
			);
		} else if (Array.isArray(ov) && Array.isArray(bv)) {
			(result as Record<string, unknown>)[key] = [...bv, ...ov];
		} else {
			(result as Record<string, unknown>)[key] = ov;
		}
	}
	return result;
}

export function parseConfig(raw: string): HeimdallConfig | null {
	try {
		const errors: ParseError[] = [];
		const parsed = parse(raw, errors, { allowTrailingComma: true });
		if (errors.length === 0 && parsed && typeof parsed === "object") return parsed;
	} catch {
		// Parse error — skip
	}
	return null;
}

function preferredConfigPath(dir: string, basename: string): string | undefined {
	const jsoncPath = join(dir, `${basename}.jsonc`);
	if (existsSync(jsoncPath)) return jsoncPath;
	const jsonPath = join(dir, `${basename}.json`);
	if (existsSync(jsonPath)) return jsonPath;
	return undefined;
}

function findRepoRoot(cwd: string): string | undefined {
	let dir = resolve(cwd);
	for (;;) {
		if (existsSync(join(dir, ".git"))) return dir;
		const parent = dirname(dir);
		if (parent === dir) return undefined;
		dir = parent;
	}
}

function findProjectConfigPath(cwd: string, basename: string): string | undefined {
	const repoRoot = findRepoRoot(cwd);
	return preferredConfigPath(join(repoRoot ?? cwd, ".pi"), basename);
}

export function loadConfigFile(path: string | undefined): HeimdallConfig | null {
	if (!path || !existsSync(path)) return null;
	return parseConfig(readFileSync(path, "utf-8"));
}

export function defaultConfigText(): string {
	const denyList = DEFAULT_PRIVATE_PATHS.map((path) => `\t\t\t\t${JSON.stringify(path)}`).join(",\n");
	return `// Generated by pi-heimdall for transparency.\n// This file may be overwritten when Heimdall starts.\n// Put local changes in heimdall.jsonc or a project .pi/heimdall.jsonc file.\n{\n\t"sandbox": {\n\t\t"enabled": false,\n\t\t"useDefaultFilesystemDeny": true,\n\t\t"sshAgent": false,\n\t\t"gpgAgent": false,\n\t\t"ageAgent": false,\n\t\t"filesystem": {\n\t\t\t"deny": [\n${denyList}\n\t\t\t],\n\t\t\t"writable": [\n\t\t\t\t"~/.pi"\n\t\t\t]\n\t\t}\n\t}\n}\n`;
}

function generatedDefaultConfigPath(agentDir: string): string {
	return join(agentDir, `${DEFAULT_CONFIG_BASENAME}.jsonc`);
}

export function ensureGeneratedDefaultConfig(agentDir: string = getAgentDir()): string {
	mkdirSync(agentDir, { recursive: true });
	const defaultPath = generatedDefaultConfigPath(agentDir);
	writeFileSync(defaultPath, defaultConfigText());
	return defaultPath;
}

function withoutGeneratedDeny(config: HeimdallConfig): HeimdallConfig {
	return {
		...config,
		sandbox: {
			...config.sandbox,
			filesystem: {
				...config.sandbox?.filesystem,
				deny: [],
			},
		},
	};
}

export function mergeConfigLevels(defaultConfig: HeimdallConfig | null, userConfig: HeimdallConfig | null, projectConfig: HeimdallConfig | null): HeimdallConfig {
	let merged = deepMerge(defaultConfig ?? {}, userConfig ?? {});
	merged = deepMerge(merged, projectConfig ?? {});

	if (merged.sandbox?.useDefaultFilesystemDeny === false && defaultConfig) {
		merged = deepMerge(withoutGeneratedDeny(defaultConfig), userConfig ?? {});
		merged = deepMerge(merged, projectConfig ?? {});
	}

	return merged;
}

export function loadEffectiveConfig(agentDir: string, cwd: string): { config: HeimdallConfig; defaultConfigPath: string; projectConfigPath: string | undefined } {
	const defaultConfigPath = ensureGeneratedDefaultConfig(agentDir);
	const userConfigPath = preferredConfigPath(agentDir, USER_CONFIG_BASENAME);
	const projectConfigPath = findProjectConfigPath(cwd, USER_CONFIG_BASENAME);

	const defaultConfig = loadConfigFile(defaultConfigPath);
	const userConfig = loadConfigFile(userConfigPath);
	const projectConfig = loadConfigFile(projectConfigPath);

	return {
		config: mergeConfigLevels(defaultConfig, userConfig, projectConfig),
		defaultConfigPath,
		projectConfigPath,
	};
}
