import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { DEFAULT_PRIVATE_PATHS } from "../lib/sandbox/default-private-paths";
import { defaultConfigText, loadConfigFile, loadEffectiveConfig } from "../lib/heimdall-config";

describe("heimdall config loading", () => {
	let tmpDir: string;
	let agentDir: string;
	let cwd: string;

	beforeEach(() => {
		tmpDir = join(tmpdir(), `heimdall-config-test-${Date.now()}-${Math.random().toString(16).slice(2)}`);
		agentDir = join(tmpDir, "agent");
		cwd = join(tmpDir, "repo");
		mkdirSync(agentDir, { recursive: true });
		mkdirSync(join(cwd, ".pi"), { recursive: true });
	});

	afterEach(() => {
		rmSync(tmpDir, { recursive: true, force: true });
	});

	it("loads JSONC config files with comments and trailing commas", () => {
		const configPath = join(agentDir, "heimdall.jsonc");
		writeFileSync(configPath, `{
			// comments are allowed
			"sandbox": {
				"enabled": true,
				"filesystem": { "writable": ["."], },
			},
		}`);

		expect(loadConfigFile(configPath)).toMatchObject({
			sandbox: { enabled: true, filesystem: { writable: ["."] } },
		});
	});

	it("does not mutate string values that contain comma-bracket sequences", () => {
		const configPath = join(agentDir, "heimdall.jsonc");
		writeFileSync(configPath, `{
			"sandbox": {
				"filesystem": {
					"virtual": { "/tmp/example": "literal ,] and ,} content" },
				},
			},
		}`);

		expect(loadConfigFile(configPath)?.sandbox?.filesystem?.virtual?.["/tmp/example"]).toBe("literal ,] and ,} content");
	});

	it("loads legacy JSON when JSONC is absent", () => {
		writeFileSync(join(agentDir, "heimdall.json"), JSON.stringify({ sandbox: { enabled: true } }));

		const { config } = loadEffectiveConfig(agentDir, cwd);

		expect(config.sandbox?.enabled).toBe(true);
	});

	it("merges legacy JSON project config on top of legacy JSON user config", () => {
		writeFileSync(join(agentDir, "heimdall.json"), JSON.stringify({
			sandbox: { enabled: true, network: "host", filesystem: { writable: ["~/user"] } },
		}));
		writeFileSync(join(cwd, ".pi", "heimdall.json"), JSON.stringify({
			sandbox: { network: "none", filesystem: { writable: ["./project"] } },
		}));

		const { config, projectConfigPath } = loadEffectiveConfig(agentDir, cwd);

		expect(config.sandbox?.enabled).toBe(true);
		expect(config.sandbox?.network).toBe("none");
		expect(config.sandbox?.filesystem?.writable).toEqual(["~/.pi", "~/user", "./project"]);
		expect(projectConfigPath).toBe(join(cwd, ".pi", "heimdall.json"));
	});

	it("prefers JSONC over JSON at user and project levels", () => {
		writeFileSync(join(agentDir, "heimdall.json"), JSON.stringify({ sandbox: { network: "json" } }));
		writeFileSync(join(agentDir, "heimdall.jsonc"), `{ "sandbox": { "network": "jsonc" } }`);
		writeFileSync(join(cwd, ".pi", "heimdall.json"), JSON.stringify({ sandbox: { proc: "json" } }));
		writeFileSync(join(cwd, ".pi", "heimdall.jsonc"), `{ "sandbox": { "proc": "jsonc" } }`);

		const { config, projectConfigPath } = loadEffectiveConfig(agentDir, cwd);

		expect(config.sandbox?.enabled).toBe(false);
		expect(config.sandbox?.network).toBe("jsonc");
		expect(config.sandbox?.proc).toBe("jsonc");
		expect(projectConfigPath).toBe(join(cwd, ".pi", "heimdall.jsonc"));
	});

	it("generates and refreshes transparent default config", () => {
		const generated = join(agentDir, "heimdall.default.jsonc");
		writeFileSync(generated, "{ \"sandbox\": { \"enabled\": true } }\n");

		const { config } = loadEffectiveConfig(agentDir, cwd);
		const text = readFileSync(generated, "utf-8");

		expect(text).toBe(defaultConfigText());
		expect(text).toContain("Generated by pi-heimdall for transparency");
		expect(config.sandbox?.enabled).toBe(false);
		expect(config.sandbox?.useDefaultFilesystemDeny).toBe(true);
		expect(config.sandbox?.sshAgent).toBe(false);
		expect(config.sandbox?.gpgAgent).toBe(false);
		expect(config.sandbox?.ageAgent).toBe(false);
		expect(config.sandbox?.filesystem?.deny).toEqual(DEFAULT_PRIVATE_PATHS);
		expect(config.sandbox?.filesystem?.writable).toEqual(["~/.pi"]);
	});

	it("merges generated defaults, user config, and project config in precedence order", () => {
		writeFileSync(join(agentDir, "heimdall.jsonc"), `{
			"sandbox": { "enabled": true, "network": "host", "filesystem": { "deny": ["~/user"] } }
		}`);
		writeFileSync(join(cwd, ".pi", "heimdall.jsonc"), `{
			"sandbox": { "network": "none", "filesystem": { "deny": ["~/project"] } }
		}`);

		const { config } = loadEffectiveConfig(agentDir, cwd);

		expect(config.sandbox?.enabled).toBe(true);
		expect(config.sandbox?.network).toBe("none");
		expect(config.sandbox?.filesystem?.deny).toEqual([...DEFAULT_PRIVATE_PATHS, "~/user", "~/project"]);
	});

	it("useDefaultFilesystemDeny false excludes generated denies but keeps explicit denies", () => {
		writeFileSync(join(agentDir, "heimdall.jsonc"), `{
			"sandbox": {
				"useDefaultFilesystemDeny": false,
				"filesystem": { "deny": ["~/.ssh", "~/user"] }
			}
		}`);
		writeFileSync(join(cwd, ".pi", "heimdall.jsonc"), `{
			"sandbox": { "filesystem": { "deny": ["~/project"] } }
		}`);

		const { config } = loadEffectiveConfig(agentDir, cwd);

		expect(config.sandbox?.useDefaultFilesystemDeny).toBe(false);
		expect(config.sandbox?.filesystem?.deny).toEqual(["~/.ssh", "~/user", "~/project"]);
	});

	it("finds project config at repo root from nested cwd", () => {
		const nestedCwd = join(cwd, "packages", "app");
		mkdirSync(nestedCwd, { recursive: true });
		mkdirSync(join(cwd, ".git"), { recursive: true });
		writeFileSync(join(agentDir, "heimdall.json"), JSON.stringify({
			sandbox: { enabled: true, network: "host" },
		}));
		writeFileSync(join(cwd, ".pi", "heimdall.json"), JSON.stringify({
			sandbox: { network: "none" },
		}));

		const { config, projectConfigPath } = loadEffectiveConfig(agentDir, nestedCwd);

		expect(config.sandbox?.enabled).toBe(true);
		expect(config.sandbox?.network).toBe("none");
		expect(projectConfigPath).toBe(join(cwd, ".pi", "heimdall.json"));
	});

	it("does not use parent .pi config outside repo root", () => {
		const parentRoot = join(tmpDir, "workspace");
		const repoRoot = join(parentRoot, "repo");
		const nestedCwd = join(repoRoot, "packages", "app");
		mkdirSync(join(parentRoot, ".pi"), { recursive: true });
		mkdirSync(join(repoRoot, ".git"), { recursive: true });
		mkdirSync(nestedCwd, { recursive: true });
		writeFileSync(join(agentDir, "heimdall.json"), JSON.stringify({
			sandbox: { enabled: true, network: "host" },
		}));
		writeFileSync(join(parentRoot, ".pi", "heimdall.json"), JSON.stringify({
			sandbox: { network: "none" },
		}));

		const { config, projectConfigPath } = loadEffectiveConfig(agentDir, nestedCwd);

		expect(config.sandbox?.enabled).toBe(true);
		expect(config.sandbox?.network).toBe("host");
		expect(projectConfigPath).toBeUndefined();
	});
});
